# Fabrizio Duroni config file.
#

# SEO config
title: Fabrizio Duroni

description: >
  Fabrizio Duroni 'Chicio' official site with profile details. Main skills: mobile application development,
  computer graphics, web development.

url: https://www.fabrizioduroni.it
author: Fabrizio Duroni
twitter:
  username: chicio86
  card: summary
facebook:
  app_id: 443203399348229
  publisher: https://www.facebook.com/fabrizio.duroni
logo: /assets/images/fabrizio-duroni.jpg
social:
  name: Fabrizio Duroni
  links:
    - https://twitter.com/chicio86
    - https://www.facebook.com/fabrizio.duroni
    - https://www.linkedin.com/in/fabrizio-duroni-947a9b35/
    - https://plus.google.com/+FabrizioDuroni
    - https://github.com/chicio
    - https://it.pinterest.com/chicio86/
lang: en_US
image: /assets/images/fabrizio-duroni.jpg

# Jekyll general Configuration
timezone: Europe/Rome
future: false
paginate: 5
paginate_path: /blog/page:num/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - gulpfile.babel.js
  - material
  - LICENSE.md
  - README.md
  - dependencies-home.html
  - dependencies-blog.html
  - dependencies-css.html
  - CNAME
  - pages-gem
  - chicio.github.io.code-workspace
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - PULL_REQUEST_TEMPLATE.md
# limit_posts: 5

# Menu
nav:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog/"
  - name: "About Me"
    url: "/2017/05/10/about-me.html"

# Jemoji config
emoji:
  src: "/assets/images/"

# RSS Feed config
feed_items: 30
feed_update_period: monthly
feed_update_frequency: 2
