name: Lighthouse

on: [workflow_dispatch]

jobs:
  build-and-test:
    name: Lighthouse Audit
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lhci
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.fabrizioduroni.it
            https://www.fabrizioduroni.it/blog/
          configPath: './.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
